"""Demo catalog content (EN canonical + UZ/RU translations).

Every organization here is FICTIONAL (`is_demo=True`): the UI labels their content as demo
content, and application links point at the reserved example.org domain. Dates are offsets
(days) from the day the seed runs, so deadlines stay meaningful in demos.
"""

TASHKENT = {"city": "Tashkent", "country": "Uzbekistan", "uz": {"city": "Toshkent", "country": "O‘zbekiston"}, "ru": {"city": "Ташкент", "country": "Узбекистан"}}
SAMARKAND = {"city": "Samarkand", "country": "Uzbekistan", "uz": {"city": "Samarqand", "country": "O‘zbekiston"}, "ru": {"city": "Самарканд", "country": "Узбекистан"}}

ORGANIZATIONS = [
    {
        "slug": "gifted-learning-lab", "name": "Gifted Learning Lab", "organization_type": "EDUCATION_CENTER", "verified": True,
        "short_description": "The Gifted team's own curated starter content.",
        "uz": {"short_description": "Gifted jamoasining o‘zi tayyorlagan boshlang‘ich materiallar."},
        "ru": {"short_description": "Стартовые материалы, подобранные командой Gifted."},
        "city": "Tashkent", "country": "Uzbekistan", "loc": TASHKENT,
    },
    {
        "slug": "future-skills-academy", "name": "Future Skills Academy", "organization_type": "EDUCATION_CENTER",
        "short_description": "Short, practical courses in design, technology and creative skills.",
        "uz": {"short_description": "Dizayn, texnologiya va ijodiy ko‘nikmalar bo‘yicha qisqa amaliy kurslar."},
        "ru": {"short_description": "Короткие практические курсы по дизайну, технологиям и творческим навыкам."},
        "city": "Tashkent", "country": "Uzbekistan", "loc": TASHKENT,
    },
    {
        "slug": "green-horizons-foundation", "name": "Green Horizons Foundation", "organization_type": "FOUNDATION",
        "short_description": "Helps young people take action for the environment in their communities.",
        "uz": {"short_description": "Yoshlarga o‘z mahallasida atrof-muhit uchun harakat qilishga yordam beradi."},
        "ru": {"short_description": "Помогает молодёжи действовать ради природы в своём районе."},
        "city": "Samarkand", "country": "Uzbekistan", "loc": SAMARKAND,
    },
    {
        "slug": "youth-discovery-network", "name": "Youth Discovery Network", "organization_type": "NGO",
        "short_description": "Leadership, entrepreneurship and language programs for teenagers.",
        "uz": {"short_description": "O‘smirlar uchun yetakchilik, tadbirkorlik va til dasturlari."},
        "ru": {"short_description": "Программы лидерства, предпринимательства и языков для подростков."},
        "city": "Tashkent", "country": "Uzbekistan", "loc": TASHKENT,
    },
    {
        "slug": "central-innovation-hub", "name": "Central Innovation Hub", "organization_type": "COMMUNITY",
        "short_description": "A maker and research space for young innovators in science and AI.",
        "uz": {"short_description": "Fan va sun’iy intellekt bo‘yicha yosh ixtirochilar uchun ustaxona va tadqiqot maskani."},
        "ru": {"short_description": "Мейкерское и исследовательское пространство для юных изобретателей в науке и ИИ."},
        "city": "Tashkent", "country": "Uzbekistan", "loc": TASHKENT,
    },
]


def _res(slug, org, rtype, category, minutes, cover, targets, exposure, en, uz, ru, *, difficulty="BEGINNER",
         evidence=(), featured=False, order=0):
    return {
        "slug": slug, "organization": org, "resource_type": rtype, "category": category, "duration_minutes": minutes,
        "cover_key": cover, "target_signals": targets, "target_exposure": exposure, "difficulty": difficulty,
        "produces_evidence": bool(evidence), "evidence_signals": list(evidence), "featured": featured, "order": order,
        "title": en[0], "short_description": en[1], "content": en[2],
        "translations": {"uz": {"title": uz[0], "short_description": uz[1], "content": uz[2]},
                         "ru": {"title": ru[0], "short_description": ru[1], "content": ru[2]}},
    }


def _c(intro, points, try_this):
    return {"intro": intro, "points": points, "try_this": try_this}


RESOURCES = [
    _res(
        "ocean-conservation-young-people", "green-horizons-foundation", "ARTICLE", "ENVIRONMENT", 8, "mountain",
        ["investigative", "value_helpfulness"], ["exp_science"],
        ("The Power of Ocean Conservation", "How young people protect oceans and rivers — and what you can do this week.",
         _c("Oceans produce much of the oxygen we breathe. Around the world, students run clean-ups, measure plastic and share what they find.",
            ["Water systems connect: what we throw away inland can reach the sea.", "Simple measurement (counting, photographing, mapping) turns worry into data.", "Small local actions add up when they are recorded and shared."],
            "Look at one bin at home or school for a day. What could have been reused?")),
        ("Okeanlarni asrashning kuchi", "Yoshlar okean va daryolarni qanday asraydi — va siz shu hafta nima qila olasiz.",
         _c("Nafas oladigan kislorodimizning katta qismini okeanlar beradi. Dunyo bo‘ylab o‘quvchilar tozalash aksiyalari o‘tkazadi, plastikni o‘lchaydi va natijalarni bo‘lishadi.",
            ["Suv tizimlari bog‘langan: quruqlikda tashlangan narsa dengizgacha yetib borishi mumkin.", "Oddiy o‘lchov (sanash, suratga olish, xaritaga tushirish) xavotirni ma’lumotga aylantiradi.", "Kichik mahalliy ishlar yozib borilsa va bo‘lishilsa, katta natija beradi."],
            "Bir kun davomida uyingiz yoki maktabingizdagi bitta chiqindi qutisini kuzating. Nimani qayta ishlatish mumkin edi?")),
        ("Сила защиты океанов", "Как молодёжь защищает океаны и реки — и что ты можешь сделать на этой неделе.",
         _c("Океаны дают значительную часть кислорода, которым мы дышим. Школьники по всему миру проводят уборки, измеряют пластик и делятся результатами.",
            ["Водные системы связаны: выброшенное на суше может попасть в море.", "Простые измерения (подсчёт, фото, карта) превращают тревогу в данные.", "Маленькие местные дела складываются, когда их записывают и показывают другим."],
            "Понаблюдай за одним мусорным ведром дома или в школе в течение дня. Что можно было использовать повторно?")),
        order=1,
    ),
    _res(
        "design-thinking-for-real-change", "future-skills-academy", "VIDEO", "ARTS", 12, "product_design",
        ["artistic", "user_thinking", "problem_solving"], ["exp_design"],
        ("Design Thinking for Real Change", "Use the design-thinking cycle to solve real problems, with examples from young innovators.",
         _c("Design thinking starts with people, not products: understand who has the problem, then try quick ideas and improve them.",
            ["Empathize: talk to the people who have the problem.", "Define: write the problem in one sentence.", "Prototype and test: build something rough, learn, repeat."],
            "Pick a small annoyance at school. Ask two people about it and write the problem in one sentence.")),
        ("Haqiqiy o‘zgarish uchun dizayn tafakkuri", "Dizayn tafakkuri bosqichlari bilan haqiqiy muammolarni hal qiling — yosh ixtirochilar misolida.",
         _c("Dizayn tafakkuri mahsulotdan emas, odamdan boshlanadi: muammo kimda ekanini tushuning, so‘ng tezkor g‘oyalarni sinab, yaxshilang.",
            ["Hamdardlik: muammosi bor odamlar bilan gaplashing.", "Aniqlash: muammoni bitta gapda yozing.", "Prototip va sinov: qo‘pol namuna yasang, o‘rganing, takrorlang."],
            "Maktabdagi kichik noqulaylikni tanlang. Bu haqda ikki kishidan so‘rang va muammoni bitta gapda yozing.")),
        ("Дизайн-мышление для реальных перемен", "Используй цикл дизайн-мышления для реальных задач — на примерах юных изобретателей.",
         _c("Дизайн-мышление начинается с людей, а не с продукта: пойми, у кого проблема, затем пробуй быстрые идеи и улучшай их.",
            ["Эмпатия: поговори с людьми, у которых есть проблема.", "Определение: сформулируй проблему одним предложением.", "Прототип и тест: сделай черновой вариант, узнай новое, повтори."],
            "Выбери мелкое неудобство в школе. Спроси о нём двух человек и запиши проблему одним предложением.")),
        order=2,
    ),
    _res(
        "social-impact-project-planner", "youth-discovery-network", "TOOLKIT", "SOCIAL_IMPACT", 30, "tutoring",
        ["social", "enterprising", "structured_planning", "value_helpfulness"], ["exp_organizing", "exp_helping"],
        ("Social Impact Project Planner", "A step-by-step worksheet to turn an idea for your community into a small, real plan.",
         _c("Good projects are small enough to start this month. This planner walks you from a problem you care about to a first action.",
            ["Choose one problem and one group of people it affects.", "Name one small, measurable goal for four weeks.", "List who can help and what you need to ask them."],
            "Fill in step 1 and share it with a friend or teacher for feedback.")),
        ("Ijtimoiy loyiha rejalashtiruvchisi", "Mahallangiz uchun g‘oyani kichik, haqiqiy rejaga aylantiradigan bosqichma-bosqich varaqa.",
         _c("Yaxshi loyiha shu oy boshlasa bo‘ladigan darajada kichik bo‘ladi. Bu rejalashtiruvchi sizni muhim muammodan birinchi harakatgacha olib boradi.",
            ["Bitta muammo va u ta’sir qiladigan bitta guruhni tanlang.", "To‘rt hafta uchun bitta kichik, o‘lchanadigan maqsad qo‘ying.", "Kim yordam bera olishini va ulardan nima so‘rashingizni yozing."],
            "1-bosqichni to‘ldiring va fikr olish uchun do‘stingiz yoki ustozingizga ko‘rsating.")),
        ("Планировщик социального проекта", "Пошаговый шаблон, чтобы превратить идею для своего района в небольшой реальный план.",
         _c("Хороший проект достаточно мал, чтобы начать его в этом месяце. Планировщик ведёт от важной для тебя проблемы к первому действию.",
            ["Выбери одну проблему и одну группу людей, которых она касается.", "Поставь одну небольшую измеримую цель на четыре недели.", "Запиши, кто может помочь и о чём их попросить."],
            "Заполни шаг 1 и покажи другу или учителю, чтобы получить отзыв.")),
        evidence=["exp_organizing"], order=3,
    ),
    _res(
        "sustainability-leadership-basics", "green-horizons-foundation", "COURSE", "ENVIRONMENT", 120, "gardening",
        ["enterprising", "social", "value_helpfulness"], ["exp_organizing"],
        ("Sustainability Leadership Basics", "Four short lessons on leading a green project: from idea to team to results.",
         _c("This short course is for anyone who wants to lead change, even without a title. Work through it at your own pace.",
            ["Lesson 1 — Why sustainability needs leaders of every age.", "Lesson 2 — Building a small team around a shared goal.", "Lesson 3 — Planning, tracking and telling your story.", "Lesson 4 — Keeping going when things are slow."],
            "After lesson 2, write down three people who might join a green project with you.")),
        ("Barqarorlik yetakchiligi asoslari", "Yashil loyihani boshqarish bo‘yicha to‘rtta qisqa dars: g‘oyadan jamoaga va natijagacha.",
         _c("Bu qisqa kurs lavozimsiz ham o‘zgarishni boshqarmoqchi bo‘lgan har kim uchun. O‘z sur’atingizda o‘ting.",
            ["1-dars — Nega barqarorlikka har yoshdagi yetakchilar kerak.", "2-dars — Umumiy maqsad atrofida kichik jamoa tuzish.", "3-dars — Rejalashtirish, kuzatish va o‘z hikoyangizni aytish.", "4-dars — Ishlar sekin ketganda ham davom etish."],
            "2-darsdan keyin siz bilan yashil loyihaga qo‘shilishi mumkin bo‘lgan uch kishini yozing.")),
        ("Основы лидерства в устойчивом развитии", "Четыре коротких урока о том, как вести зелёный проект: от идеи к команде и результатам.",
         _c("Этот короткий курс для всех, кто хочет вести перемены, даже без должности. Проходи в своём темпе.",
            ["Урок 1 — Почему устойчивому развитию нужны лидеры любого возраста.", "Урок 2 — Как собрать небольшую команду вокруг общей цели.", "Урок 3 — Планирование, отслеживание и рассказ о результатах.", "Урок 4 — Как продолжать, когда дело идёт медленно."],
            "После урока 2 запиши трёх человек, которые могли бы присоединиться к твоему зелёному проекту.")),
        difficulty="INTERMEDIATE", evidence=["exp_organizing"], featured=True, order=4,
    ),
    _res(
        "reduce-waste-at-school", "green-horizons-foundation", "TOOLKIT", "ENVIRONMENT", 25, "gardening",
        ["social", "value_practical"], ["exp_organizing"],
        ("Reduce Waste at School Toolkit", "A ready-made checklist for a one-week waste audit with your class.",
         _c("A waste audit shows what your school throws away — and where the easiest wins are.",
            ["Day 1–2: count and sort what one classroom throws away.", "Day 3: find the top three items.", "Day 4–5: try one change and count again."],
            "Ask your class teacher if you can run the day-1 count.")),
        ("Maktabda chiqindini kamaytirish to‘plami", "Sinfingiz bilan bir haftalik chiqindi tekshiruvi uchun tayyor ro‘yxat.",
         _c("Chiqindi tekshiruvi maktabingiz nimani tashlayotganini va eng oson yutuqlar qayerdaligini ko‘rsatadi.",
            ["1–2-kun: bitta sinf tashlaydigan narsalarni sanang va saralang.", "3-kun: eng ko‘p uchraydigan uchta narsani toping.", "4–5-kun: bitta o‘zgarishni sinab ko‘ring va qayta sanang."],
            "Sinf rahbaringizdan 1-kundagi sanashni o‘tkazishga ruxsat so‘rang.")),
        ("Набор «Меньше отходов в школе»", "Готовый чек-лист для недельного аудита отходов вместе с классом.",
         _c("Аудит отходов показывает, что выбрасывает школа и где проще всего что-то улучшить.",
            ["Дни 1–2: посчитайте и рассортируйте, что выбрасывает один класс.", "День 3: найдите три самых частых предмета.", "Дни 4–5: попробуйте одно изменение и посчитайте снова."],
            "Спроси классного руководителя, можно ли провести подсчёт первого дня.")),
        evidence=["exp_organizing"], order=5,
    ),
    _res(
        "build-your-first-ai-model", "central-innovation-hub", "COURSE", "AI_TECH", 90, "data",
        ["realistic", "logical_reasoning", "investigative"], ["exp_technology"],
        ("Build Your First AI Model", "Understand how machines learn from examples — no coding experience needed to start.",
         _c("AI models learn patterns from examples. In this course you sort data, train a tiny model with a free online tool and test where it fails.",
            ["Lesson 1 — What 'learning from examples' means.", "Lesson 2 — Collecting fair, balanced examples.", "Lesson 3 — Training and testing a simple image model.", "Lesson 4 — When AI gets it wrong, and why that matters."],
            "Collect 10 photos of two kinds of objects. Which ones would be hard for a computer to tell apart?")),
        ("Birinchi sun’iy intellekt modelingizni yarating", "Mashinalar misollardan qanday o‘rganishini tushuning — boshlash uchun dasturlash tajribasi shart emas.",
         _c("SI modellari misollardan qonuniyatlarni o‘rganadi. Bu kursda ma’lumotlarni saralaysiz, bepul onlayn vosita bilan kichik model o‘qitasiz va u qayerda xato qilishini sinaysiz.",
            ["1-dars — «Misollardan o‘rganish» nimani anglatadi.", "2-dars — Adolatli, muvozanatli misollar yig‘ish.", "3-dars — Oddiy tasvir modelini o‘qitish va sinash.", "4-dars — SI xato qilganda va bu nega muhim."],
            "Ikki xil narsaning 10 tadan suratini to‘plang. Qaysilarini kompyuter ajrata olishi qiyin bo‘ladi?")),
        ("Создай свою первую модель ИИ", "Пойми, как машины учатся на примерах, — для старта не нужен опыт программирования.",
         _c("Модели ИИ находят закономерности в примерах. На курсе ты рассортируешь данные, обучишь маленькую модель в бесплатном онлайн-инструменте и проверишь, где она ошибается.",
            ["Урок 1 — Что значит «учиться на примерах».", "Урок 2 — Как собрать честные, сбалансированные примеры.", "Урок 3 — Обучение и проверка простой модели изображений.", "Урок 4 — Когда ИИ ошибается и почему это важно."],
            "Собери по 10 фото двух видов предметов. Какие из них компьютеру будет трудно различить?")),
        difficulty="INTERMEDIATE", evidence=["exp_technology"], order=6,
    ),
    _res(
        "intro-to-robotics", "central-innovation-hub", "VIDEO", "STEM", 15, "robotics",
        ["realistic", "spatial_reasoning", "problem_solving"], ["exp_technology"],
        ("How Robots Sense and Move", "A short visual guide to sensors, motors and the simple logic behind every robot.",
         _c("Every robot does three things: senses the world, decides, and acts. This guide breaks down each part with everyday examples.",
            ["Sensors turn light, distance or touch into numbers.", "A controller follows rules: if this, then that.", "Motors and servos turn decisions into movement."],
            "Find three machines at home that sense something. What do they measure?")),
        ("Robotlar qanday sezadi va harakatlanadi", "Sensorlar, motorlar va har bir robot ortidagi oddiy mantiq haqida qisqa ko‘rgazmali qo‘llanma.",
         _c("Har bir robot uch ish qiladi: atrofni sezadi, qaror qiladi va harakat qiladi. Qo‘llanma har bir qismni kundalik misollar bilan tushuntiradi.",
            ["Sensorlar yorug‘lik, masofa yoki teginishni raqamlarga aylantiradi.", "Boshqaruvchi qoidaga amal qiladi: agar bu bo‘lsa — unda shu.", "Motorlar qarorlarni harakatga aylantiradi."],
            "Uyingizda nimanidir sezadigan uchta qurilmani toping. Ular nimani o‘lchaydi?")),
        ("Как роботы чувствуют и двигаются", "Короткий наглядный гид о датчиках, моторах и простой логике внутри любого робота.",
         _c("Любой робот делает три вещи: воспринимает мир, принимает решение и действует. Гид разбирает каждую часть на бытовых примерах.",
            ["Датчики превращают свет, расстояние или касание в числа.", "Контроллер следует правилам: если это — то то.", "Моторы и сервоприводы превращают решения в движение."],
            "Найди дома три устройства, которые что-то измеряют. Что именно?")),
        order=7,
    ),
    _res(
        "pitch-your-idea-in-60-seconds", "youth-discovery-network", "TOOLKIT", "ENTREPRENEURSHIP", 20, "leadership_2",
        ["enterprising", "value_originality", "social"], ["exp_organizing"],
        ("Pitch Your Idea in 60 Seconds", "A simple template to explain any idea clearly: problem, solution, why you, next step.",
         _c("A pitch is a short story about a problem worth solving. This template keeps it to four sentences.",
            ["Problem: who struggles, and with what?", "Solution: what you would try first.", "Why you: what you've seen or done that others haven't.", "Ask: the one thing you need next."],
            "Record yourself pitching an idea in under 60 seconds. Listen back once and cut one sentence.")),
        ("G‘oyangizni 60 soniyada taqdim eting", "Har qanday g‘oyani aniq tushuntirish uchun oddiy shablon: muammo, yechim, nega siz, keyingi qadam.",
         _c("Taqdimot — hal qilishga arziydigan muammo haqida qisqa hikoya. Bu shablon uni to‘rt gapda ushlab turadi.",
            ["Muammo: kim, nimada qiynalyapti?", "Yechim: birinchi nimani sinab ko‘rardingiz.", "Nega siz: boshqalar ko‘rmagan nimani ko‘rgansiz yoki qilgansiz.", "So‘rov: keyingi qadam uchun kerak bo‘lgan bitta narsa."],
            "G‘oyangizni 60 soniyadan kam vaqtda aytib, ovozingizni yozib oling. Bir marta tinglang va bitta gapni qisqartiring.")),
        ("Презентуй идею за 60 секунд", "Простой шаблон, чтобы ясно объяснить любую идею: проблема, решение, почему ты, следующий шаг.",
         _c("Питч — это короткая история о проблеме, которую стоит решить. Шаблон укладывает её в четыре предложения.",
            ["Проблема: кому и с чем трудно?", "Решение: что бы ты попробовал(а) первым.", "Почему ты: что ты видел(а) или делал(а), чего не делали другие.", "Просьба: одна вещь, которая нужна дальше."],
            "Запиши, как ты рассказываешь идею меньше чем за 60 секунд. Послушай один раз и убери одно предложение.")),
        order=8,
    ),
    _res(
        "sketchbook-habit", "future-skills-academy", "TOOLKIT", "ARTS", 15, "art_studio",
        ["artistic", "value_originality"], ["exp_design"],
        ("The 10-Minute Sketchbook Habit", "Daily prompts to build a creative habit — no drawing skills required.",
         _c("Creativity grows with small, regular practice. Ten minutes a day is enough to notice your own style.",
            ["Draw what you see, not what you know: pick one object a day.", "Mix media: tape in tickets, leaves or colours.", "Once a week, flip back and circle what surprised you."],
            "Today: draw the view from where you're sitting in exactly ten minutes.")),
        ("10 daqiqalik eskiz daftari odati", "Ijodiy odat shakllantirish uchun kunlik topshiriqlar — rasm chizish mahorati shart emas.",
         _c("Ijodkorlik kichik va muntazam mashq bilan o‘sadi. Kuniga o‘n daqiqa o‘z uslubingizni sezish uchun yetarli.",
            ["Bilganingizni emas, ko‘rganingizni chizing: kuniga bitta buyum tanlang.", "Materiallarni aralashtiring: chipta, barg yoki ranglarni yopishtiring.", "Haftada bir marta orqaga varaqlab, sizni hayratlantirgan narsani belgilang."],
            "Bugun: o‘tirgan joyingizdan ko‘rinadigan manzarani aynan o‘n daqiqada chizing.")),
        ("Привычка «скетчбук за 10 минут»", "Ежедневные задания для творческой привычки — умение рисовать не требуется.",
         _c("Творчество растёт от небольшой регулярной практики. Десяти минут в день хватит, чтобы заметить свой стиль.",
            ["Рисуй то, что видишь, а не то, что знаешь: один предмет в день.", "Смешивай материалы: вклеивай билеты, листья, цвета.", "Раз в неделю листай назад и отмечай, что тебя удивило."],
            "Сегодня: нарисуй вид с того места, где сидишь, ровно за десять минут.")),
        evidence=["exp_design"], order=9,
    ),
    _res(
        "learn-a-language-through-projects", "youth-discovery-network", "ARTICLE", "LANGUAGES", 10, "tutoring_2",
        ["social", "value_discovery"], ["exp_helping"],
        ("Learn a Language Through Projects", "Why using a language for something real beats memorising lists.",
         _c("People remember words they needed. Project-based learning gives you a reason to use a new language every week.",
            ["Pick a project you'd enjoy anyway: a recipe video, a comic, an interview.", "Learn only the words that project needs.", "Share the result with someone who speaks the language."],
            "Write five sentences about your day in the language you're learning.")),
        ("Tilni loyihalar orqali o‘rganing", "Nega tilni haqiqiy ish uchun ishlatish ro‘yxat yodlashdan samaraliroq.",
         _c("Odamlar kerak bo‘lgan so‘zlarni eslab qoladi. Loyiha asosida o‘rganish yangi tilni har hafta ishlatishga sabab beradi.",
            ["Baribir yoqadigan loyihani tanlang: retsept videosi, komiks, intervyu.", "Faqat o‘sha loyihaga kerak so‘zlarni o‘rganing.", "Natijani o‘sha tilda gapiradigan odamga ko‘rsating."],
            "O‘rganayotgan tilingizda kuningiz haqida beshta gap yozing.")),
        ("Учи язык через проекты", "Почему язык лучше учить на реальных задачах, а не зубрёжкой списков.",
         _c("Мы запоминаем слова, которые нам были нужны. Проектное обучение даёт повод использовать новый язык каждую неделю.",
            ["Выбери проект, который тебе и так интересен: видео-рецепт, комикс, интервью.", "Учи только те слова, которые нужны проекту.", "Покажи результат тому, кто говорит на этом языке."],
            "Напиши пять предложений о своём дне на языке, который учишь.")),
        order=10,
    ),
    _res(
        "plan-your-week", "gifted-learning-lab", "ARTICLE", "PERSONAL_DEVELOPMENT", 6, "mountain",
        ["structured_planning", "prioritization", "independent_work"], [],
        ("Plan Your Week Without Stress", "A three-step weekly plan that leaves room for school, rest and the things you're exploring.",
         _c("A plan isn't a strict timetable — it's a way to make sure the important things get a place in your week.",
            ["Sunday: list everything, then circle only three priorities.", "Give each priority a day and a time.", "Leave one free evening on purpose."],
            "Write your three priorities for next week on a sticky note.")),
        ("Haftangizni stresssiz rejalashtiring", "Maktab, dam olish va o‘rganayotgan ishlaringizga joy qoldiradigan uch bosqichli haftalik reja.",
         _c("Reja — qat’iy jadval emas, muhim ishlar haftangizda o‘rin topishiga ishonch hosil qilish usuli.",
            ["Yakshanba: hammasini yozing, so‘ng faqat uchta ustuvor ishni belgilang.", "Har bir ustuvor ishga kun va vaqt bering.", "Ataylab bitta bo‘sh kechani qoldiring."],
            "Keyingi hafta uchun uchta ustuvor ishingizni yopishqoq qog‘ozga yozing.")),
        ("Планируй неделю без стресса", "План недели в три шага, в котором есть место учёбе, отдыху и тому, что ты исследуешь.",
         _c("План — это не жёсткое расписание, а способ убедиться, что у важных дел есть место в неделе.",
            ["В воскресенье: запиши всё, потом обведи только три приоритета.", "Дай каждому приоритету день и время.", "Специально оставь один свободный вечер."],
            "Запиши три приоритета на следующую неделю на стикере.")),
        order=11,
    ),
    _res(
        "how-scientists-ask-questions", "gifted-learning-lab", "ARTICLE", "STEM", 8, "science_lab",
        ["investigative", "value_discovery"], ["exp_science"],
        ("How Scientists Ask Questions", "Turn everyday curiosity into a question you can actually test.",
         _c("Science begins with a good question — one you can answer by observing or measuring something.",
            ["Start with 'I wonder…' and write down what you notice.", "Make it testable: what would you change, and what would you measure?", "Predict before you test, then compare."],
            "Write three 'I wonder' questions about something in your kitchen. Circle the one you could test today.")),
        ("Olimlar qanday savol beradi", "Kundalik qiziqishni haqiqatan sinab ko‘rsa bo‘ladigan savolga aylantiring.",
         _c("Fan yaxshi savoldan boshlanadi — kuzatish yoki o‘lchash orqali javob topsa bo‘ladigan savoldan.",
            ["«Qiziq, nega…» deb boshlang va nimani sezganingizni yozing.", "Sinab bo‘ladigan qiling: nimani o‘zgartirasiz va nimani o‘lchaysiz?", "Sinashdan oldin taxmin qiling, keyin solishtiring."],
            "Oshxonangizdagi biror narsa haqida uchta «Qiziq, nega…» savolini yozing. Bugun sinab ko‘rsa bo‘ladiganini belgilang.")),
        ("Как учёные задают вопросы", "Преврати повседневное любопытство в вопрос, который можно проверить.",
         _c("Наука начинается с хорошего вопроса — такого, на который можно ответить наблюдением или измерением.",
            ["Начни с «Интересно, почему…» и запиши, что замечаешь.", "Сделай вопрос проверяемым: что ты изменишь и что измеришь?", "Сделай прогноз до опыта, потом сравни."],
            "Запиши три вопроса «Интересно, почему…» о чём-то на кухне. Отметь тот, который можно проверить сегодня.")),
        featured=True, order=0,
    ),
]

LEARNING_PATH = {
    "slug": "create-a-more-sustainable-world", "organization": "green-horizons-foundation", "category": "ENVIRONMENT",
    "cover_key": "gardening", "difficulty": "BEGINNER", "featured": True,
    "title": "Create a More Sustainable World",
    "description": "Explore real-world solutions, learn from young changemakers, and plan how you can make a positive impact in your community.",
    "translations": {
        "uz": {"title": "Barqarorroq dunyo yarating", "description": "Hayotiy yechimlarni o‘rganing, yosh o‘zgarish yetakchilaridan o‘rganing va mahallangizga qanday ijobiy ta’sir qilishni rejalashtiring."},
        "ru": {"title": "Сделай мир устойчивее", "description": "Изучи реальные решения, поучись у юных лидеров перемен и спланируй, как принести пользу своему району."},
    },
    "items": [
        "ocean-conservation-young-people", "design-thinking-for-real-change", "reduce-waste-at-school",
        "social-impact-project-planner", "sustainability-leadership-basics",
    ],
}


def _opp(slug, org, otype, category, mode, cover, ages, deadline, program, targets, exposure, en, uz, ru, *,
         loc=None, global_available=False, opens=None, featured=False):
    loc = loc or {}
    return {
        "slug": slug, "organization": org, "opportunity_type": otype, "category": category, "mode": mode,
        "cover_key": cover, "age_min": ages[0], "age_max": ages[1], "deadline_days": deadline, "program_days": program,
        "open_days": opens, "target_signals": targets, "target_exposure": exposure, "global_available": global_available,
        "featured": featured, "city": loc.get("city", ""), "country": loc.get("country", ""),
        "application_url": f"https://example.org/gifted-demo/{slug}",
        "title": en["title"], "short_description": en["short"], "description": en["description"],
        "skills": en["skills"], "eligibility": en["eligibility"], "faqs": en["faqs"],
        "translations": {
            lang: {
                "title": d["title"], "short_description": d["short"], "description": d["description"],
                "skills": d["skills"], "eligibility": d["eligibility"], "faqs": d["faqs"],
                **({"country": loc[lang]["country"]} if loc else {}),
                **({"city": loc[lang]["city"]} if loc.get("city") else {}),
            }
            for lang, d in (("uz", uz), ("ru", ru))
        },
    }


def _faq(*pairs):
    return [{"q": q, "a": a} for q, a in pairs]


OPPORTUNITIES = [
    _opp(
        "young-innovators-research-fellowship", "central-innovation-hub", "FELLOWSHIP", "STEM", "ONLINE", "microscope",
        (15, 18), 40, (60, 116), ["investigative", "independent_work", "value_discovery", "logical_reasoning"], ["exp_science"],
        {"title": "Young Innovators Research Fellowship", "short": "An 8-week online program where you work with mentors on a real research question.",
         "description": "Fellows choose a question about climate, health or cities, learn basic research methods with a mentor, and present their findings at an online showcase.",
         "skills": ["Research & inquiry", "Analytical thinking", "Problem solving", "Communication"],
         "eligibility": ["Ages 15–18", "About 4 hours a week for 8 weeks", "A short statement about a question you care about"],
         "faqs": _faq(("Does it cost anything?", "The demo listing says the program is free for participants."), ("Do I need research experience?", "No. Curiosity and a question you care about are enough to apply."))},
        {"title": "Yosh ixtirochilar tadqiqot stipendiyasi", "short": "Mentorlar bilan haqiqiy tadqiqot savoli ustida ishlaydigan 8 haftalik onlayn dastur.",
         "description": "Ishtirokchilar iqlim, salomatlik yoki shaharlar haqida savol tanlaydi, mentor bilan tadqiqot asoslarini o‘rganadi va natijalarni onlayn ko‘rgazmada taqdim etadi.",
         "skills": ["Tadqiqot va izlanish", "Tahliliy fikrlash", "Muammolarni hal qilish", "Muloqot"],
         "eligibility": ["15–18 yosh", "8 hafta davomida haftasiga taxminan 4 soat", "Sizni qiziqtirgan savol haqida qisqa bayonot"],
         "faqs": _faq(("Pullikmi?", "Demo e’londa dastur ishtirokchilar uchun bepul deb ko‘rsatilgan."), ("Tadqiqot tajribasi kerakmi?", "Yo‘q. Ariza berish uchun qiziquvchanlik va sizga muhim savol yetarli."))},
        {"title": "Исследовательская стипендия «Юные инноваторы»", "short": "8-недельная онлайн-программа: работа с наставником над настоящим исследовательским вопросом.",
         "description": "Участники выбирают вопрос о климате, здоровье или городах, осваивают основы исследования с наставником и представляют результаты на онлайн-показе.",
         "skills": ["Исследование", "Аналитическое мышление", "Решение задач", "Коммуникация"],
         "eligibility": ["Возраст 15–18 лет", "Около 4 часов в неделю в течение 8 недель", "Короткий текст о вопросе, который тебе важен"],
         "faqs": _faq(("Это платно?", "В демо-объявлении программа указана как бесплатная для участников."), ("Нужен ли опыт исследований?", "Нет. Для заявки достаточно любопытства и важного для тебя вопроса."))},
        global_available=True, featured=True,
    ),
    _opp(
        "global-student-innovation-challenge", "future-skills-academy", "COMPETITION", "ARTS", "HYBRID", "product_design",
        (13, 18), 21, (35, 65), ["artistic", "problem_solving", "value_originality", "user_thinking"], ["exp_design"],
        {"title": "Student Innovation Challenge", "short": "Design a solution for a more sustainable school. Teams of 2–4 present to a jury.",
         "description": "Teams research a sustainability problem at their school, prototype a solution and present it online or at the final day in Tashkent.",
         "skills": ["Design thinking", "Prototyping", "Teamwork", "Presenting"],
         "eligibility": ["Ages 13–18", "Teams of 2–4 students", "One adult supporter (teacher or parent)"],
         "faqs": _faq(("Can I join without a team?", "The demo listing says solo applicants are matched into teams."), ("Is the final in person?", "It is hybrid: teams may present online or in Tashkent."))},
        {"title": "O‘quvchilar innovatsiya tanlovi", "short": "Barqarorroq maktab uchun yechim loyihalang. 2–4 kishilik jamoalar hakamlarga taqdim etadi.",
         "description": "Jamoalar maktabidagi barqarorlik muammosini o‘rganadi, yechim prototipini yasaydi va uni onlayn yoki Toshkentdagi final kunida taqdim etadi.",
         "skills": ["Dizayn tafakkuri", "Prototiplash", "Jamoaviy ish", "Taqdimot"],
         "eligibility": ["13–18 yosh", "2–4 o‘quvchidan iborat jamoa", "Bitta katta yoshli ko‘makchi (ustoz yoki ota-ona)"],
         "faqs": _faq(("Jamoasiz qatnasha olamanmi?", "Demo e’longa ko‘ra, yakka ishtirokchilar jamoalarga biriktiriladi."), ("Final yuzma-yuzmi?", "Aralash: jamoalar onlayn yoki Toshkentda taqdim etishi mumkin."))},
        {"title": "Конкурс школьных инноваций", "short": "Придумай решение для более экологичной школы. Команды из 2–4 человек выступают перед жюри.",
         "description": "Команды изучают экологическую проблему своей школы, делают прототип решения и представляют его онлайн или в финальный день в Ташкенте.",
         "skills": ["Дизайн-мышление", "Прототипирование", "Командная работа", "Презентация"],
         "eligibility": ["Возраст 13–18 лет", "Команды из 2–4 школьников", "Один взрослый наставник (учитель или родитель)"],
         "faqs": _faq(("Можно участвовать без команды?", "По демо-объявлению, одиночных участников объединяют в команды."), ("Финал очный?", "Смешанный: можно выступать онлайн или в Ташкенте."))},
        loc=TASHKENT,
    ),
    _opp(
        "ai-builders-weekend-hackathon", "central-innovation-hub", "HACKATHON", "AI_TECH", "IN_PERSON", "robotics_girl",
        (14, 18), 9, (16, 17), ["realistic", "logical_reasoning", "problem_solving"], ["exp_technology"],
        {"title": "AI Builders Weekend Hackathon", "short": "Two days to build a small AI-powered tool with mentors. Beginners welcome.",
         "description": "Work in small teams to build a simple tool that uses AI responsibly — for example, sorting recycling photos or helping plan study time. Mentors run short workshops throughout.",
         "skills": ["Coding basics", "Working with data", "Teamwork", "Responsible AI"],
         "eligibility": ["Ages 14–18", "Bring a laptop if you have one (some are available)", "Parent/guardian consent for the weekend"],
         "faqs": _faq(("Do I need to know how to code?", "No — the demo listing includes beginner teams."), ("Are meals included?", "The demo listing says lunch is provided on both days."))},
        {"title": "AI Builders dam olish kunlari xakatoni", "short": "Mentorlar bilan kichik SI vositasini yaratish uchun ikki kun. Yangi boshlovchilar ham kutiladi.",
         "description": "Kichik jamoalarda SIdan mas’uliyat bilan foydalanadigan oddiy vosita yarating — masalan, qayta ishlanadigan chiqindilar suratlarini saralash yoki o‘qish vaqtini rejalash. Mentorlar qisqa mashg‘ulotlar o‘tkazadi.",
         "skills": ["Dasturlash asoslari", "Ma’lumotlar bilan ishlash", "Jamoaviy ish", "Mas’uliyatli SI"],
         "eligibility": ["14–18 yosh", "Imkoningiz bo‘lsa noutbuk olib keling (ba’zilari beriladi)", "Ota-ona yoki vasiy roziligi"],
         "faqs": _faq(("Dasturlashni bilishim kerakmi?", "Yo‘q — demo e’londa yangi boshlovchilar jamoalari ham bor."), ("Ovqat beriladimi?", "Demo e’longa ko‘ra, ikkala kuni ham tushlik beriladi."))},
        {"title": "Хакатон выходного дня AI Builders", "short": "Два дня, чтобы с наставниками собрать небольшой инструмент на ИИ. Новичкам рады.",
         "description": "В небольших командах соберите простой инструмент, который ответственно использует ИИ, — например, сортирует фото вторсырья или помогает планировать учёбу. Наставники проводят короткие мастер-классы.",
         "skills": ["Основы программирования", "Работа с данными", "Командная работа", "Ответственный ИИ"],
         "eligibility": ["Возраст 14–18 лет", "Возьми ноутбук, если есть (часть выдаётся)", "Согласие родителя или опекуна"],
         "faqs": _faq(("Нужно уметь программировать?", "Нет — в демо-объявлении есть команды для новичков."), ("Будет ли питание?", "По демо-объявлению, обед предоставляется оба дня."))},
        loc=TASHKENT,
    ),
    _opp(
        "future-changemakers-leadership-camp", "youth-discovery-network", "CAMP", "LEADERSHIP", "IN_PERSON", "leadership",
        (14, 18), 30, (50, 56), ["enterprising", "social", "structured_planning"], ["exp_organizing"],
        {"title": "Future Changemakers Leadership Camp", "short": "A one-week camp to build leadership, communication and project skills.",
         "description": "Campers practise facilitation, public speaking and project planning, then design a small community project to run after the camp.",
         "skills": ["Leadership", "Public speaking", "Project planning", "Collaboration"],
         "eligibility": ["Ages 14–18", "Available for the full week", "A short answer: a change you'd like to see in your community"],
         "faqs": _faq(("Where do campers stay?", "The demo listing describes a residential camp near Samarkand."), ("Is there support with costs?", "The demo listing mentions a limited number of free places."))},
        {"title": "Kelajak yetakchilari lageri", "short": "Yetakchilik, muloqot va loyiha ko‘nikmalarini rivojlantiradigan bir haftalik lager.",
         "description": "Ishtirokchilar muhokamani boshqarish, omma oldida so‘zlash va loyiha rejalashtirishni mashq qiladi, so‘ng lagerdan keyin amalga oshiriladigan kichik mahalla loyihasini ishlab chiqadi.",
         "skills": ["Yetakchilik", "Omma oldida so‘zlash", "Loyiha rejalashtirish", "Hamkorlik"],
         "eligibility": ["14–18 yosh", "Butun hafta davomida band bo‘lmaslik", "Qisqa javob: mahallangizda qanday o‘zgarishni ko‘rmoqchisiz"],
         "faqs": _faq(("Qayerda yashaladi?", "Demo e’londa Samarqand yaqinidagi turar joyli lager tasvirlangan."), ("Xarajatlar bo‘yicha yordam bormi?", "Demo e’londa cheklangan miqdorda bepul o‘rinlar borligi aytilgan."))},
        {"title": "Лагерь лидерства «Будущие лидеры перемен»", "short": "Недельный лагерь для развития лидерства, коммуникации и проектных навыков.",
         "description": "Участники тренируют фасилитацию, публичные выступления и планирование, а затем разрабатывают небольшой проект для своего района после лагеря.",
         "skills": ["Лидерство", "Публичные выступления", "Планирование проектов", "Сотрудничество"],
         "eligibility": ["Возраст 14–18 лет", "Возможность участвовать всю неделю", "Короткий ответ: какие перемены ты хочешь видеть в своём районе"],
         "faqs": _faq(("Где живут участники?", "В демо-объявлении описан лагерь с проживанием под Самаркандом."), ("Есть ли помощь с расходами?", "В демо-объявлении упомянуто ограниченное число бесплатных мест."))},
        loc=SAMARKAND,
    ),
    _opp(
        "creative-portfolio-workshop", "future-skills-academy", "WORKSHOP", "ARTS", "ONLINE", "art_studio",
        (12, 17), 18, (25, 25), ["artistic", "value_originality"], ["exp_design"],
        {"title": "Creative Portfolio Workshop", "short": "A live online workshop on collecting your drawings, designs and projects into a simple portfolio.",
         "description": "In two hours you'll learn how to choose your best work, explain your process and put together a one-page portfolio you can keep improving.",
         "skills": ["Visual storytelling", "Self-reflection", "Presentation"],
         "eligibility": ["Ages 12–17", "Any creative work — drawings, crafts, photos, digital designs"],
         "faqs": _faq(("Do I need special software?", "No. A phone camera and paper are enough."), ("Will it be recorded?", "The demo listing says a recording is shared with registered participants."))},
        {"title": "Ijodiy portfolio mashg‘uloti", "short": "Rasmlaringiz, dizaynlaringiz va loyihalaringizni oddiy portfolioga jamlash bo‘yicha jonli onlayn mashg‘ulot.",
         "description": "Ikki soat ichida eng yaxshi ishlaringizni tanlash, ish jarayoningizni tushuntirish va doim yaxshilab boriladigan bir sahifalik portfolio tuzishni o‘rganasiz.",
         "skills": ["Vizual hikoya", "O‘z-o‘zini tahlil", "Taqdimot"],
         "eligibility": ["12–17 yosh", "Har qanday ijodiy ish — rasm, qo‘l mehnati, surat, raqamli dizayn"],
         "faqs": _faq(("Maxsus dastur kerakmi?", "Yo‘q. Telefon kamerasi va qog‘oz yetarli."), ("Yozib olinadimi?", "Demo e’longa ko‘ra, yozuv ro‘yxatdan o‘tganlarga yuboriladi."))},
        {"title": "Мастер-класс «Творческое портфолио»", "short": "Живой онлайн-мастер-класс: как собрать рисунки, дизайны и проекты в простое портфолио.",
         "description": "За два часа ты научишься выбирать лучшие работы, объяснять свой процесс и соберёшь одностраничное портфолио, которое можно улучшать.",
         "skills": ["Визуальный рассказ", "Рефлексия", "Презентация"],
         "eligibility": ["Возраст 12–17 лет", "Любые творческие работы — рисунки, поделки, фото, цифровой дизайн"],
         "faqs": _faq(("Нужны ли специальные программы?", "Нет. Достаточно камеры телефона и бумаги."), ("Будет ли запись?", "По демо-объявлению, запись отправят зарегистрированным участникам."))},
        global_available=True,
    ),
    _opp(
        "stem-excellence-scholarship", "future-skills-academy", "SCHOLARSHIP", "STEM", "ONLINE", "data",
        (15, 18), 55, (90, 270), ["investigative", "logical_reasoning", "independent_work"], [],
        {"title": "STEM Excellence Scholarship", "short": "Covers a year of online STEM courses for students in Uzbekistan who show curiosity and persistence.",
         "description": "Scholars get free access to a year of online STEM courses and a monthly check-in with a mentor. Selection looks at motivation and a short project, not only grades.",
         "skills": ["Mathematics", "Scientific thinking", "Self-directed learning"],
         "eligibility": ["Ages 15–18", "Studying in Uzbekistan", "A short project or experiment you did (any size)"],
         "faqs": _faq(("Are grades required?", "The demo listing asks for a short project; grades are optional."), ("What does it cover?", "Course access and mentor check-ins, according to the demo listing."))},
        {"title": "STEM a’lochilari granti", "short": "O‘zbekistonda qiziquvchan va qat’iyatli o‘quvchilar uchun bir yillik onlayn STEM kurslari.",
         "description": "Grant sohiblari bir yil davomida onlayn STEM kurslaridan bepul foydalanadi va har oy mentor bilan uchrashadi. Tanlovda faqat baholar emas, motivatsiya va qisqa loyiha ham hisobga olinadi.",
         "skills": ["Matematika", "Ilmiy fikrlash", "Mustaqil o‘rganish"],
         "eligibility": ["15–18 yosh", "O‘zbekistonda o‘qish", "O‘zingiz qilgan qisqa loyiha yoki tajriba (har qanday hajmda)"],
         "faqs": _faq(("Baholar talab qilinadimi?", "Demo e’londa qisqa loyiha so‘raladi; baholar ixtiyoriy."), ("Nimalarni qoplaydi?", "Demo e’longa ko‘ra, kurslarga kirish va mentor bilan uchrashuvlar."))},
        {"title": "Стипендия STEM Excellence", "short": "Год онлайн-курсов STEM для школьников в Узбекистане, которые проявляют любопытство и упорство.",
         "description": "Стипендиаты получают бесплатный доступ к году онлайн-курсов STEM и ежемесячные встречи с наставником. При отборе смотрят на мотивацию и небольшой проект, а не только на оценки.",
         "skills": ["Математика", "Научное мышление", "Самостоятельное обучение"],
         "eligibility": ["Возраст 15–18 лет", "Учёба в Узбекистане", "Небольшой проект или опыт, который ты сделал(а)"],
         "faqs": _faq(("Нужны ли оценки?", "В демо-объявлении просят небольшой проект; оценки необязательны."), ("Что покрывает стипендия?", "По демо-объявлению — доступ к курсам и встречи с наставником."))},
        loc={**TASHKENT, "city": ""},
    ),
    _opp(
        "young-entrepreneurs-program", "youth-discovery-network", "PROGRAM", "ENTREPRENEURSHIP", "HYBRID", "leadership_2",
        (14, 18), 45, (70, 130), ["enterprising", "value_practical", "prioritization", "value_originality"], ["exp_organizing"],
        {"title": "Young Entrepreneurs Program", "short": "Eight weekend sessions to test a small business or social idea with real customers.",
         "description": "Participants learn how to talk to customers, test an idea cheaply and present results at a demo day. Sessions alternate between online and Tashkent.",
         "skills": ["Customer interviews", "Budgeting basics", "Pitching", "Decision-making"],
         "eligibility": ["Ages 14–18", "An idea or a problem you'd like to solve", "Available on Saturdays"],
         "faqs": _faq(("Do I need money to start?", "No. The demo listing focuses on low-cost experiments."), ("Can friends join together?", "Yes — teams of up to three, according to the demo listing."))},
        {"title": "Yosh tadbirkorlar dasturi", "short": "Kichik biznes yoki ijtimoiy g‘oyani haqiqiy mijozlar bilan sinash uchun sakkizta dam olish kuni mashg‘uloti.",
         "description": "Ishtirokchilar mijozlar bilan suhbatlashish, g‘oyani arzon sinash va natijalarni namoyish kunida taqdim etishni o‘rganadi. Mashg‘ulotlar navbat bilan onlayn va Toshkentda o‘tadi.",
         "skills": ["Mijoz bilan suhbat", "Byudjet asoslari", "Taqdimot", "Qaror qabul qilish"],
         "eligibility": ["14–18 yosh", "Hal qilmoqchi bo‘lgan g‘oya yoki muammo", "Shanba kunlari bo‘sh bo‘lish"],
         "faqs": _faq(("Boshlash uchun pul kerakmi?", "Yo‘q. Demo e’lon arzon tajribalarga qaratilgan."), ("Do‘stlar bilan birga qatnashsa bo‘ladimi?", "Ha — demo e’longa ko‘ra, uch kishigacha jamoa."))},
        {"title": "Программа «Юные предприниматели»", "short": "Восемь занятий по выходным, чтобы проверить бизнес- или социальную идею с реальными клиентами.",
         "description": "Участники учатся говорить с клиентами, дёшево проверять идеи и представлять результаты на демо-дне. Занятия чередуются: онлайн и в Ташкенте.",
         "skills": ["Интервью с клиентами", "Основы бюджета", "Питч", "Принятие решений"],
         "eligibility": ["Возраст 14–18 лет", "Идея или проблема, которую хочется решить", "Свободные субботы"],
         "faqs": _faq(("Нужны ли деньги на старт?", "Нет. Демо-объявление делает упор на недорогие эксперименты."), ("Можно участвовать с друзьями?", "Да — по демо-объявлению, командами до трёх человек."))},
        loc=TASHKENT,
    ),
    _opp(
        "green-futures-volunteer-days", "green-horizons-foundation", "VOLUNTEERING", "ENVIRONMENT", "IN_PERSON", "gardening",
        (12, 18), None, (None, None), ["social", "value_helpfulness", "value_practical"], ["exp_helping", "exp_organizing"],
        {"title": "Green Futures Volunteer Days", "short": "Monthly tree-planting and park clean-up days. Join one day or all of them.",
         "description": "Volunteers plant trees, map litter hot spots and help run activities for younger children. Each day ends with a short reflection circle.",
         "skills": ["Teamwork", "Environmental action", "Helping others"],
         "eligibility": ["Ages 12–18", "Under-16s come with a parent/guardian's consent"],
         "faqs": _faq(("How often can I come?", "Any volunteer day — sign-up is rolling in the demo listing."), ("What should I bring?", "Water, a hat and comfortable shoes."))},
        {"title": "Green Futures ko‘ngillilar kunlari", "short": "Har oylik daraxt ekish va bog‘ tozalash kunlari. Bir kunga yoki hammasiga qo‘shiling.",
         "description": "Ko‘ngillilar daraxt ekadi, axlat ko‘p joylarni xaritaga tushiradi va kichik bolalar uchun mashg‘ulotlar o‘tkazishga yordam beradi. Har kun qisqa fikr almashish bilan yakunlanadi.",
         "skills": ["Jamoaviy ish", "Ekologik harakat", "Boshqalarga yordam"],
         "eligibility": ["12–18 yosh", "16 yoshgacha bo‘lganlar ota-ona yoki vasiy roziligi bilan"],
         "faqs": _faq(("Qanchalik tez-tez kelishim mumkin?", "Istalgan ko‘ngillilar kuniga — demo e’londa ro‘yxatdan o‘tish doimiy ochiq."), ("Nima olib kelish kerak?", "Suv, bosh kiyim va qulay poyabzal."))},
        {"title": "Волонтёрские дни Green Futures", "short": "Ежемесячные посадки деревьев и уборка парков. Приходи на один день или на все.",
         "description": "Волонтёры сажают деревья, отмечают на карте места скопления мусора и помогают проводить занятия для младших детей. Каждый день заканчивается коротким кругом обсуждения.",
         "skills": ["Командная работа", "Экологические действия", "Помощь другим"],
         "eligibility": ["Возраст 12–18 лет", "До 16 лет — с согласия родителя или опекуна"],
         "faqs": _faq(("Как часто можно приходить?", "На любой волонтёрский день — в демо-объявлении запись открыта постоянно."), ("Что взять с собой?", "Воду, головной убор и удобную обувь."))},
        loc=SAMARKAND,
    ),
    _opp(
        "language-exchange-meetups", "youth-discovery-network", "EVENT", "LANGUAGES", "ONLINE", "tutoring_2",
        (13, 18), None, (None, None), ["social", "value_discovery"], ["exp_helping"],
        {"title": "Language Exchange Meetups", "short": "Friendly online meetups to practise English, Uzbek or Russian in small groups.",
         "description": "Every other week, small moderated groups practise a language through games and short conversations. Cameras are optional.",
         "skills": ["Speaking confidence", "Listening", "Cultural curiosity"],
         "eligibility": ["Ages 13–18", "Any level — beginners welcome"],
         "faqs": _faq(("Is it moderated?", "Yes — every group has a trained adult host, according to the demo listing."), ("Do I have to turn on my camera?", "No, cameras are optional."))},
        {"title": "Til almashish uchrashuvlari", "short": "Kichik guruhlarda ingliz, o‘zbek yoki rus tilini mashq qilish uchun do‘stona onlayn uchrashuvlar.",
         "description": "Har ikki haftada kichik moderatsiyali guruhlar o‘yinlar va qisqa suhbatlar orqali tilni mashq qiladi. Kamera ixtiyoriy.",
         "skills": ["Gapirishda ishonch", "Tinglash", "Madaniyatlarga qiziqish"],
         "eligibility": ["13–18 yosh", "Har qanday daraja — yangi boshlovchilar ham kutiladi"],
         "faqs": _faq(("Moderatsiya qilinadimi?", "Ha — demo e’longa ko‘ra, har bir guruhda tayyorlangan katta yoshli boshlovchi bor."), ("Kamerani yoqishim shartmi?", "Yo‘q, kamera ixtiyoriy."))},
        {"title": "Языковые встречи-обмены", "short": "Дружелюбные онлайн-встречи, чтобы практиковать английский, узбекский или русский в небольших группах.",
         "description": "Раз в две недели небольшие модерируемые группы практикуют язык через игры и короткие разговоры. Камера по желанию.",
         "skills": ["Уверенность в речи", "Аудирование", "Интерес к культурам"],
         "eligibility": ["Возраст 13–18 лет", "Любой уровень — новичкам рады"],
         "faqs": _faq(("Встречи модерируются?", "Да — по демо-объявлению, в каждой группе есть обученный взрослый ведущий."), ("Нужно включать камеру?", "Нет, камера по желанию."))},
        global_available=True,
    ),
    _opp(
        "junior-lab-assistant-internship", "central-innovation-hub", "INTERNSHIP", "STEM", "IN_PERSON", "science_lab",
        (16, 18), -3, (20, 60), ["investigative", "realistic", "structured_planning"], ["exp_science", "exp_technology"],
        {"title": "Junior Lab Assistant Internship", "short": "A part-time summer internship helping run experiments in a youth maker lab.",
         "description": "Interns help prepare experiments, keep lab notes and support younger visitors during open-lab hours.",
         "skills": ["Lab safety", "Careful observation", "Record keeping"],
         "eligibility": ["Ages 16–18", "Available two afternoons a week", "Interest in science or technology"],
         "faqs": _faq(("Is it paid?", "The demo listing describes a stipend for travel."), ("Will it open again?", "The demo listing says applications reopen each spring."))},
        {"title": "Laboratoriya yordamchisi amaliyoti", "short": "Yoshlar ustaxonasida tajribalar o‘tkazishga yordam beradigan yarim kunlik yozgi amaliyot.",
         "description": "Amaliyotchilar tajribalarni tayyorlashga yordam beradi, laboratoriya yozuvlarini yuritadi va ochiq laboratoriya soatlarida kichik mehmonlarga ko‘maklashadi.",
         "skills": ["Laboratoriya xavfsizligi", "Diqqat bilan kuzatish", "Yozuv yuritish"],
         "eligibility": ["16–18 yosh", "Haftasiga ikki kun tushdan keyin bo‘sh bo‘lish", "Fan yoki texnologiyaga qiziqish"],
         "faqs": _faq(("Haq to‘lanadimi?", "Demo e’londa yo‘l xarajatlari uchun stipendiya ko‘rsatilgan."), ("Yana ochiladimi?", "Demo e’longa ko‘ra, arizalar har bahorda qayta ochiladi."))},
        {"title": "Стажировка «Младший лаборант»", "short": "Летняя стажировка на неполный день: помощь в проведении опытов в молодёжной мейкер-лаборатории.",
         "description": "Стажёры помогают готовить эксперименты, ведут лабораторные записи и помогают младшим посетителям в часы открытой лаборатории.",
         "skills": ["Техника безопасности", "Внимательное наблюдение", "Ведение записей"],
         "eligibility": ["Возраст 16–18 лет", "Свободны два дня в неделю после обеда", "Интерес к науке или технологиям"],
         "faqs": _faq(("Стажировка оплачивается?", "В демо-объявлении указана компенсация проезда."), ("Откроется ли снова?", "По демо-объявлению, приём заявок открывается каждую весну."))},
        loc=TASHKENT,
    ),
]

CIRCLES = [
    ("science-circle", "Science Circle", "STEM", "science_lab", "flask", ["investigative", "exp_science"],
     "Share experiments, ask questions and explore the wonders of science.",
     ("Fan to‘garagi", "Tajribalar bilan bo‘lishing, savollar bering va fan mo‘jizalarini o‘rganing."),
     ("Научный круг", "Делитесь опытами, задавайте вопросы и открывайте чудеса науки.")),
    ("design-lab", "Design Lab", "ARTS", "product_design", "palette", ["artistic", "user_thinking"],
     "Explore creativity, product design and human-centred solutions.",
     ("Dizayn laboratoriyasi", "Ijodkorlik, mahsulot dizayni va insonga yo‘naltirilgan yechimlarni o‘rganing."),
     ("Дизайн-лаборатория", "Творчество, продуктовый дизайн и решения, ориентированные на людей.")),
    ("young-entrepreneurs", "Young Entrepreneurs", "ENTREPRENEURSHIP", "leadership_2", "rocket", ["enterprising", "value_practical"],
     "Test ideas, talk about projects and learn how to make things happen.",
     ("Yosh tadbirkorlar", "G‘oyalarni sinang, loyihalarni muhokama qiling va ishni amalga oshirishni o‘rganing."),
     ("Юные предприниматели", "Проверяйте идеи, обсуждайте проекты и учитесь доводить дело до конца.")),
    ("changemakers", "Changemakers", "SOCIAL_IMPACT", "tutoring", "people", ["social", "value_helpfulness"],
     "Turn ideas into impact — a space for social innovation and community action.",
     ("O‘zgarish yetakchilari", "G‘oyalarni ta’sirga aylantiring — ijtimoiy innovatsiya va mahalla ishlari uchun makon."),
     ("Лидеры перемен", "Превращайте идеи в пользу — пространство для социальных инноваций и дел в своём районе.")),
    ("ai-builders", "AI Builders", "AI_TECH", "robotics", "cpu", ["realistic", "logical_reasoning", "exp_technology"],
     "Build, code and tinker with technology and AI — responsibly.",
     ("AI Builders", "Texnologiya va SI bilan mas’uliyatli tarzda yarating, kod yozing va tajriba qiling."),
     ("AI Builders", "Создавайте, программируйте и экспериментируйте с технологиями и ИИ — ответственно.")),
    ("green-futures", "Green Futures", "ENVIRONMENT", "gardening", "leaf", ["value_practical", "value_helpfulness"],
     "Ideas and action for a more sustainable and fair planet.",
     ("Yashil kelajak", "Barqarorroq va adolatli sayyora uchun g‘oyalar va harakatlar."),
     ("Зелёное будущее", "Идеи и действия для более устойчивой и справедливой планеты.")),
    ("language-explorers", "Language Explorers", "LANGUAGES", "tutoring_2", "globe", ["value_discovery"],
     "Practise languages, swap tips and discover new cultures together.",
     ("Til kashfiyotchilari", "Tillarni mashq qiling, maslahatlar almashing va birga yangi madaniyatlarni kashf eting."),
     ("Исследователи языков", "Практикуйте языки, делитесь советами и открывайте новые культуры вместе.")),
]

# (circle slug, org slug | None, days ahead, hour, duration h, mode, en(title, desc, location), uz, ru)
EVENTS = [
    ("design-lab", "future-skills-academy", 6, 16, 2, "ONLINE",
     ("Design for a Better Tomorrow", "A virtual workshop on sketching solutions for everyday problems.", "Online"),
     ("Yaxshiroq ertangi kun uchun dizayn", "Kundalik muammolarga yechim chizish bo‘yicha virtual mashg‘ulot.", "Onlayn"),
     ("Дизайн для лучшего завтра", "Онлайн-мастер-класс: как набрасывать решения повседневных проблем.", "Онлайн")),
    ("ai-builders", "central-innovation-hub", 9, 15, 2, "ONLINE",
     ("AI Builders Open Lab", "Bring a question about AI or a project you're stuck on. Mentors answer live.", "Online"),
     ("AI Builders ochiq laboratoriyasi", "SI haqida savol yoki to‘xtab qolgan loyihangizni olib keling. Mentorlar jonli javob beradi.", "Onlayn"),
     ("Открытая лаборатория AI Builders", "Приходи с вопросом об ИИ или проектом, на котором застрял(а). Наставники отвечают вживую.", "Онлайн")),
    ("green-futures", "green-horizons-foundation", 12, 17, 1, "ONLINE",
     ("Careers in Climate Action", "A panel conversation with people working on climate projects.", "Online"),
     ("Iqlim bo‘yicha kasblar", "Iqlim loyihalarida ishlayotgan odamlar bilan panel suhbati.", "Onlayn"),
     ("Профессии в климатической повестке", "Панельная беседа с людьми, которые работают над климатическими проектами.", "Онлайн")),
    ("changemakers", "central-innovation-hub", 20, 15, 3, "IN_PERSON",
     ("Student Innovation Showcase", "Students present community projects. Visitors welcome.", "Tashkent"),
     ("O‘quvchilar innovatsiyalari ko‘rgazmasi", "O‘quvchilar mahalla loyihalarini taqdim etadi. Mehmonlar kutiladi.", "Toshkent"),
     ("Выставка школьных инноваций", "Школьники представляют проекты для своего района. Гостям рады.", "Ташкент")),
]

# Demo peer posts (peer emails from seed_demo_engagement). Written by (fictional) learners in
# their own language and shown exactly as written — community posts are never translated.
# (peer index, circle, post type, hours ago, body)
POSTS = [
    (1, "design-lab", "ACHIEVEMENT", 2, "Just finished a cardboard prototype for a lunchbox that keeps soup warm longer. Tested it with my brother — 3 out of 5 😄 Next version soon!"),
    (2, "science-circle", "QUESTION", 20, "Does anyone know a simple experiment to show how solar panels work? For a school project, nothing expensive."),
    (3, "changemakers", "IDEA", 30, "Idea: a book swap shelf in our school corridor. Anyone done this before? How did you keep it tidy?"),
    (4, "ai-builders", "SHARE", 48, "Bugun birinchi marta rasm aniqlaydigan kichik model o‘qitdim. Mushuk va itni ajratadi, lekin pomidorni mushuk deb o‘ylayapti 😅"),
    (5, "green-futures", "ACHIEVEMENT", 60, "Мы с классом посадили 12 деревьев возле школы! В следующем месяце будем следить, сколько приживётся."),
    (6, "language-explorers", "QUESTION", 75, "What helped you most when you started speaking a new language out loud? I understand a lot but freeze when I speak."),
    (1, "young-entrepreneurs", "SHARE", 96, "Sold my first 10 hand-painted bookmarks at the school fair. Learned that people liked the small ones more than the big ones."),
    (2, "science-circle", "SHARE", 120, "Tip: if you grow beans in a clear jar you can see the roots every day. Mine grew 4 cm in a week."),
]

# Demo peers who are members of each circle (real membership rows → real member counts).
MEMBERS = {
    "science-circle": [2, 4, 5], "design-lab": [1, 3], "young-entrepreneurs": [1, 3, 6],
    "changemakers": [3, 5], "ai-builders": [4, 2], "green-futures": [5, 3, 6], "language-explorers": [6],
}
