# Generated by Django 5.2.17 on 2026-09-24 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_type', models.CharField(choices=[('PROFILE_SYNTHESIS', 'Profile synthesis + next step')], max_length=32)),
                ('input_version', models.CharField(max_length=32)),
                ('source', models.CharField(choices=[('AI', 'AI'), ('FALLBACK', 'Deterministic fallback')], max_length=8)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='assessments.assessmentsession')),
            ],
            options={
                'db_table': 'ai_insight',
                'constraints': [models.UniqueConstraint(fields=('session', 'generation_type', 'input_version'), name='uniq_ai_insight_per_session_type_version')],
            },
        ),
    ]
