# Generated by Django 5.2.17 on 2026-09-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinsight',
            name='generation_type',
            field=models.CharField(choices=[('PROFILE_SYNTHESIS', 'Profile synthesis + next step'), ('PARENT_INSIGHT', 'Parent insight')], max_length=32),
        ),
    ]
