# Generated by Django 5.2.17 on 2026-09-25 06:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_aiinsight_generation_type'),
        ('assessments', '0004_assessment_translations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aiinsight',
            name='uniq_ai_insight_per_session_type_version',
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='language',
            field=models.CharField(default='en', max_length=5),
        ),
        migrations.AddConstraint(
            model_name='aiinsight',
            constraint=models.UniqueConstraint(fields=('session', 'generation_type', 'input_version', 'language'), name='uniq_ai_insight_per_session_type_version_lang'),
        ),
    ]
