# Generated by Django 5.2.17 on 2026-09-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_remove_aiinsight_uniq_ai_insight_per_session_type_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='latency_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='schema_version',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
