# Generated by Django 5.2.17 on 2026-09-24 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('INTEREST', 'Interest'), ('APTITUDE', 'Aptitude'), ('WORK_STYLE', 'Work style'), ('VALUE', 'Value'), ('EXPOSURE', 'Exposure')], db_index=True, max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'signals_signal',
            },
        ),
        migrations.CreateModel(
            name='ResponseSignalMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_maps', to='questions.questionoption')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_maps', to='signals.signal')),
            ],
            options={
                'db_table': 'signals_response_map',
                'unique_together': {('option', 'signal')},
            },
        ),
        migrations.CreateModel(
            name='LearnerSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('confidence', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=8)),
                ('evidence_count', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to=settings.AUTH_USER_MODEL)),
                ('source_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assessments.assessmentsession')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_scores', to='signals.signal')),
            ],
            options={
                'db_table': 'signals_learner_signal',
                'ordering': ['-score'],
                'unique_together': {('learner', 'signal')},
            },
        ),
    ]
