# Generated by Django 5.2.17 on 2026-09-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnersignal',
            name='opportunity_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
