# Generated by Django 5.2.17 on 2026-09-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_learnersignal_opportunity_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
