# Generated by Django 5.2.17 on 2026-09-26 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanionConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'companion_conversation',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CompanionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('client_id', models.UUIDField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='companion.companionconversation')),
                ('reply_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='companion.companionmessage')),
            ],
            options={
                'db_table': 'companion_message',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='companionconversation',
            index=models.Index(fields=['learner', '-updated_at'], name='companion_c_learner_355dc4_idx'),
        ),
        migrations.AddConstraint(
            model_name='companionmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('client_id__isnull', False)), fields=('conversation', 'client_id'), name='uniq_companion_client_id_per_conversation'),
        ),
    ]
