# Generated by Django 5.2.17 on 2026-09-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companionmessage',
            name='diary_offer',
            field=models.CharField(choices=[('NONE', 'No offer'), ('OFFERED', 'Offered'), ('DISMISSED', 'Kept only in chat')], default='NONE', max_length=10),
        ),
    ]
