# Generated by Django 5.2.17 on 2026-09-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0002_companionmessage_diary_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='companionmessage',
            name='ai_model',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='companionmessage',
            name='ai_provider',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='companionmessage',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
