# Generated by Django 5.2.17 on 2026-09-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='last_evidence_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
