# Generated by Django 5.2.17 on 2026-09-26 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NudgeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nudge_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'today_nudge_state',
            },
        ),
        migrations.CreateModel(
            name='DailySpark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('spark_key', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('DONE', 'Done'), ('DISMISSED', 'Set aside for today')], default='NEW', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sparks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'today_daily_spark',
                'constraints': [models.UniqueConstraint(fields=('learner', 'day'), name='uniq_daily_spark')],
            },
        ),
    ]
