# Generated by Django 5.2.17 on 2026-09-24 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('context', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate')], default='BEGINNER', max_length=16)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=8)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'missions_mission',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MissionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_attempts', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='missions.mission')),
            ],
            options={
                'db_table': 'missions_attempt',
                'unique_together': {('learner', 'mission')},
            },
        ),
        migrations.CreateModel(
            name='MissionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40)),
                ('type', models.CharField(choices=[('CONTEXT', 'Context'), ('MULTI_SELECT', 'Choose several'), ('BUDGET', 'Prioritize within a budget'), ('SINGLE_CHOICE', 'Choose one'), ('REFLECTION', 'Reflection')], max_length=16)),
                ('title', models.CharField(max_length=150)),
                ('prompt', models.TextField(blank=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='missions.mission')),
            ],
            options={
                'db_table': 'missions_step',
                'ordering': ['order', 'id'],
                'unique_together': {('mission', 'key')},
            },
        ),
        migrations.CreateModel(
            name='MissionSignalMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.CharField(blank=True, max_length=40)),
                ('kind', models.CharField(choices=[('INTEREST', 'Interest'), ('EXPOSURE', 'Exposure'), ('ENGAGEMENT', 'Engagement'), ('DECISION', 'Decision-making'), ('REASONING', 'Reasoning'), ('REFLECTION', 'Reflection')], max_length=12)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('observation', models.CharField(blank=True, max_length=200)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_maps', to='missions.mission')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='signals.signal')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='missions.missionstep')),
            ],
            options={
                'db_table': 'missions_signal_map',
            },
        ),
        migrations.CreateModel(
            name='MissionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='missions.missionattempt')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='missions.missionstep')),
            ],
            options={
                'db_table': 'missions_response',
                'unique_together': {('attempt', 'step')},
            },
        ),
    ]
