# Generated by Django 5.2.17 on 2026-09-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='missionstep',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
