# Generated by Django 5.2.17 on 2026-09-26 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=240)),
                ('points_required', models.PositiveIntegerField()),
                ('reward_type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('COURSE', 'Course'), ('EVENT', 'Event'), ('COMMUNITY', 'Community'), ('MENTOR', 'Mentor')], max_length=12)),
                ('image_key', models.CharField(max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('one_per_learner', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('translations', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'engagement_reward',
                'ordering': ['order', 'points_required'],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved (awaiting the Gifted team)'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='RESERVED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='engagement.reward')),
            ],
            options={
                'db_table': 'engagement_reward_redemption',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ASSESSMENT_COMPLETED', 'Assessment completed'), ('ASSESSMENT_PROGRESS', 'Assessment progress'), ('MISSION_COMPLETED', 'Mission completed'), ('DIARY_ENTRY_CREATED', 'Diary entry created'), ('FIRST_DIARY_ENTRY', 'First diary entry bonus'), ('STREAK_7_DAYS', '7-day streak bonus')], max_length=32)),
                ('source_key', models.CharField(max_length=80)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('occurred_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'engagement_activity_event',
                'ordering': ['-occurred_on', '-id'],
                'indexes': [models.Index(fields=['occurred_on', 'learner'], name='engagement__occurre_03d989_idx'), models.Index(fields=['learner', 'occurred_on'], name='engagement__learner_9ac23f_idx')],
                'constraints': [models.UniqueConstraint(fields=('learner', 'event_type', 'source_key'), name='uniq_activity_event')],
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_key', models.CharField(max_length=40)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'engagement_student_badge',
                'constraints': [models.UniqueConstraint(fields=('learner', 'badge_key'), name='uniq_student_badge')],
            },
        ),
    ]
