# Generated by Django 5.2.17 on 2026-09-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('ASSESSMENT_COMPLETED', 'Assessment completed'), ('ASSESSMENT_PROGRESS', 'Assessment progress'), ('MISSION_COMPLETED', 'Mission completed'), ('DIARY_ENTRY_CREATED', 'Diary entry created'), ('FIRST_DIARY_ENTRY', 'First diary entry bonus'), ('STREAK_7_DAYS', '7-day streak bonus'), ('MINI_CHALLENGE', 'Daily mini challenge')], max_length=32),
        ),
    ]
