# Generated by Django 5.2.17 on 2026-09-26 05:32

import apps.diary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companion', '0002_companionmessage_diary_offer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField(blank=True)),
                ('mood', models.CharField(blank=True, choices=[('very_low', 'Very low'), ('low', 'Low'), ('neutral', 'Okay'), ('good', 'Good'), ('great', 'Great')], max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('stickers', models.JSONField(blank=True, default=list)),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate)),
                ('source', models.CharField(choices=[('MANUAL', 'Written in the diary'), ('COMPANION', 'Saved from an AI Companion chat')], default='MANUAL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companion_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_entry', to='companion.companionmessage')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diary_entry',
                'ordering': ['-entry_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DiaryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=200, storage=apps.diary.models.PrivateStorage(), upload_to=apps.diary.models.attachment_path)),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='diary.diaryentry')),
            ],
            options={
                'db_table': 'diary_attachment',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='diaryentry',
            index=models.Index(fields=['learner', '-entry_date'], name='diary_entry_learner_73d419_idx'),
        ),
    ]
