# Generated by Django 5.2.17 on 2026-09-26 09:36

import apps.diary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryattachment',
            name='image',
            field=models.FileField(max_length=200, storage=apps.diary.models.private_storage, upload_to=apps.diary.models.attachment_path),
        ),
    ]
