# Generated by Django 5.2.17 on 2026-09-26 09:32

import apps.parents.models
from django.db import migrations, models
from django.utils import timezone


def expire_legacy_codes(apps, schema_editor):
    # Pre-existing codes were permanent 5-digit codes: invalidate them instead of granting 72h.
    apps.get_model("parents", "LearnerConnectionCode").objects.update(expires_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerconnectioncode',
            name='expires_at',
            field=models.DateTimeField(default=apps.parents.models.default_expiry),
        ),
        migrations.AddField(
            model_name='learnerconnectioncode',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learnerconnectioncode',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learnerconnectioncode',
            name='code',
            field=models.CharField(default=apps.parents.models.new_code, max_length=16, unique=True),
        ),
        migrations.RunPython(expire_legacy_codes, migrations.RunPython.noop),
    ]
