# Generated by Django 5.2.17 on 2026-09-24 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questions.question'),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questions.questionoption'),
        ),
        migrations.AddField(
            model_name='assessmentsection',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.assessmentsession'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentsection',
            unique_together={('assessment', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentresponse',
            unique_together={('session', 'question')},
        ),
    ]
