# Generated by Django 5.2.17 on 2026-09-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_remove_assessmentresponse_selected_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assessmentsection',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
