# Generated by Django 5.2.17 on 2026-09-26 09:33

import django.db.models.deletion
from django.db import migrations, models


def fix_scoring_versions(apps, schema_editor):
    # The field defaulted to "v1" and was never set. Sessions of the V2 Discovery Assessment were
    # scored with rules s2; older (v1 assessment) sessions keep their value.
    Session = apps.get_model("assessments", "AssessmentSession")
    Session.objects.filter(assessment__slug="gifted-discovery").update(scoring_version="s2")


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_assessment_translations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_versions', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='assessment_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='result_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentsession',
            name='scoring_version',
            field=models.CharField(default='s2', max_length=20),
        ),
        migrations.RunPython(fix_scoring_versions, migrations.RunPython.noop),
    ]
