# Generated by Django 5.2.17 on 2026-09-24 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('ASSESSMENT', 'Assessment'), ('MISSION', 'Exploration mission'), ('VIRTUAL_LAB', 'Virtual lab'), ('OPPORTUNITY', 'Opportunity'), ('REAL_WORLD', 'Real-world activity')], db_index=True, max_length=16)),
                ('source_id', models.PositiveBigIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evidence_evidence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('INTEREST', 'Interest'), ('EXPOSURE', 'Exposure'), ('ENGAGEMENT', 'Engagement'), ('DECISION', 'Decision-making'), ('REASONING', 'Reasoning'), ('REFLECTION', 'Reflection')], max_length=12)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('observation', models.CharField(blank=True, max_length=300)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='evidence.evidence')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='signals.signal')),
            ],
            options={
                'db_table': 'evidence_signal_evidence',
            },
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_id'), name='uniq_evidence_per_source'),
        ),
        migrations.AlterUniqueTogether(
            name='signalevidence',
            unique_together={('evidence', 'signal')},
        ),
    ]
