# Generated by Django 5.2.17 on 2026-09-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='source_type',
            field=models.CharField(choices=[('ASSESSMENT', 'Assessment'), ('MISSION', 'Exploration mission'), ('VIRTUAL_LAB', 'Virtual lab'), ('OPPORTUNITY', 'Opportunity'), ('REAL_WORLD', 'Real-world activity'), ('RESOURCE', 'Learning resource')], db_index=True, max_length=16),
        ),
    ]
