# Generated by Django 5.2.17 on 2026-09-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('SINGLE_CHOICE', 'Single choice'), ('VISUAL_CHOICE', 'Visual choice (image cards)'), ('STORY_CHOICE', 'Story choice (short text options)'), ('SCENARIO_CHOICE', 'Situational choice (scenario card)'), ('VALUE_TRADEOFF', 'Values trade-off (two options)'), ('MULTI_SELECT', 'Multi-select'), ('PATTERN_CHOICE', 'Reasoning puzzle')], default='SINGLE_CHOICE', max_length=32),
        ),
    ]
