# Generated by Django 5.2.17 on 2026-09-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_content_questionoption_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
